spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-internationalization?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password:
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
  freemarker:
    expose-request-attributes: true
    expose-session-attributes: true
    charset: UTF-8
    settings:
          locale: en_US
          auto_import: /spring.ftl as spring

 # INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages # Comma-separated list of basenames, each following the ResourceBundle convention.
    cache-seconds: -1 # Loaded resource bundle files cache expiration, in seconds. When set to -1, bundles are cached forever.
    encoding: UTF-8 # Message bundles encoding.
    fallback-to-system-locale: true # Set whether to fall back to the system Locale if no files for a specific Locale have been found.
logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR