# Server settings (ServerProperties)
server:
  port: 9090
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /
security:
  user:
    password: password
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-study-cases
    username: root
    password:
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
  hibernate:
    ddl-auto : create
    naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect